### ISSUE TITLE
BFC 深入理解

### ISSUE THREAD

**Issue by VenenoFSD** [VenenoFSD/Blog#44]
# BFC 深入理解

BFC：**Block Formatting Context**，翻译过来就是**块格式化上下文**，可以把 BFC 简单理解为一种特殊的盒子的定义。当满足以下某一条件时，就形成了 BFC：

> 1. 根元素或包含根元素的元素
> 2. 元素的 float 不为 none
> 3. 元素的 position 为 absolute 或 fixed
> 4. 元素的 display 为 inline-block、table-cell、table-caption、table、table-row、 
   table-row-group、table-header-group、table-footer-group、 inline-table、flow-root
> 5. overflow 值不为 visible 的块元素
> 6. contain 值为 layout、content 或 strict 的元素
> 7. display 为 flex、inline-flex、grid、inline-grid 元素的直接子元素
> 8. 元素的 column-count 或 column-width 不为 auto，包括 column-count 为 1
> 9. column-span 为 all 的元素始终会创建一个新的BFC，即使该元素没有包裹在一个多列容器中

若一个盒子为 BFC，则它有如下的属性：

1. BFC 中的盒子会在垂直方向，一个接一个地放置。

2. Box 垂直方向的距离由 margin 决定，同一个 BFC 的两个相邻盒子的 margin 会发生重叠。
对于一个盒子来说，它由四部分组成，从外到内分别是：margin，border，padding，content，对于相邻的两个盒子，它们垂直方向上的距离取决于它们的 margin，并且距离并不是两个盒子的 margin 相加，因为在同一 BFC 内，两个盒子的 margin 会发生重叠，如下图：

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-2-1.gif)

若想要避免 margin 重叠，只需要给其中一个盒子包上一个 div，这样两个盒子分属两个 BFC，就不会发生 margin 重叠的情况。

3. BFC 中的所有盒子默认都左对齐，且这些盒子的左外边距与 BFC 容器的左边缘相接触；即使子盒子是浮动定位也是如此，左浮的盒子会与父元素左边缘接触，右浮的盒子会与父元素的右边缘接触。除非子盒子有 margin 撑开，否则上述一直成立。

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-2-2.jpg)

这里便引出了 BFC 的一个作用：清除浮动。当一个盒子不是 BFC 的时候，若它的子盒子浮动，那它无法将子盒子包裹起来，只要给这个盒子加上 **overflow: hidden** 让其成为 BFC，就可以清除浮动，代码及效果如下所示：

```html
<div class="box">
 <div class="son1"></div>
 <div class="son2"></div>
 111
</div>
```

```css
.box {
 width: 200px;
 margin: 100px auto;
 overflow: hidden;
}
.son1 {
 width: 50px;
 height: 50px;
 background-color: red;
 float: left;
}
.son2 {
 width: 50px;
 height: 50px;
 background-color: black;
 float: left;
}
```

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-2-3.gif)

4. BFC 盒子不会与浮动的盒子重叠。如果有两个相邻的非 BFC 盒子，第一个浮动，那么这两个盒子会重叠，如果第二个盒子为 BFC，则不会重叠，代码及效果如下所示：

```html
<div class="box1"></div>
<div class="box2"></div>
```

```css
.box1 {
 width: 50px;
 height: 50px;
 background-color: red;
 float: left;
}
.box2 {
 width: 100px;
 height: 100px;
 background-color: black;
 overflow: hidden;
}
```

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-2-4.gif)

在这里可以引出 BFC 的第二个作用：自适应两栏布局。只要设置第一栏的盒子浮动，第二栏盒子为 BFC，那么第二栏可自动根据父元素的宽度调整宽度，代码及效果如下所示：

```html
<div class="father">
 <div class="son1"></div>
 <div class="son2"></div>
</div>
```

```css
.father {
 width: 400px;
 height: 50px;
 border: 1px solid #000;
}
.son1 {
 width: 50px;
 height: 100%;
 background-color: red;
 float: left;
}
.son2 {
 height: 100%;
 background-color: yellow;
 overflow: hidden;
}
```

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-2-5.gif)

5. BFC 在页面上是一个隔离的独立容器，容器里面的子元素不会影响到外面的元素，反之也如此。
