### ISSUE TITLE
CSS 自定义浏览器滚动条

### ISSUE THREAD

**Issue by VenenoFSD** [VenenoFSD/Blog#45]
# CSS 自定义浏览器滚动条

在开发时有时需要我们自定义浏览器的滚动条样式，以往我们都是通过 JavaScript 来实现的，其实在支持 WebKit 的浏览器（例如 Chrome，Safari）中，可直接通过 CSS 对浏览器样式进行修改。

我们可以通过以下七个伪类选择器去修改样式：

> ::-webkit-scrollbar 滚动条本身的背景。①
> ::-webkit-scrollbar-button 滚动条上的方向按钮。②
> ::-webkit-scrollbar-track 滚动条轨道区域。③
> ::-webkit-scrollbar-track-piece 滚动条空白区域轨道。④
> ::-webkit-scrollbar-thumb 滚动条上的拖动按钮。⑤
> ::-webkit-scrollbar-corner 滚动条轨道上的底角。⑥
> ::-webkit-resizer 可调整大小的按钮。⑦

分别对应下图的七个位置：

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-3-1.png)

举个简单的例子：

```css
::-webkit-scrollbar {
  width: 6px;
  background-color: #F5F5F5;
} 
::-webkit-scrollbar-thumb {
  background-color: #000000;
}
::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
  background-color: #F5F5F5;
}
```

效果如下：

![](https://raw.githubusercontent.com/VenenoFSD/Blog/master/pic/others/css-3-2.png)
